### ISSUE TITLE
Prometheus not starting

### ISSUE THREAD

**Issue by sgoranson** [featheredtoast/satisfactory-monitoring#1]
Great project! I've having trouble with the prometheus container not starting. I'm using Docker on Windows WSL. 

If I remove power.yml it starts fine. 

`ts=2024-03-29T14:52:15.384Z caller=manager.go:200 level=error component="rule manager" msg="loading groups failed" err="/etc/prometheus/rules/power.yml: yaml: unmarshal errors:\n  line 2: field annotations not found in type rulefmt.RuleGroups\n  line 43: field description not found in type rulefmt.RuleGroups\n  line 44: field editable not found in type rulefmt.RuleGroups\n  line 45: field fiscalYearStartMonth not found in type rulefmt.RuleGroups\n  line 46: field graphTooltip not found in type rulefmt.RuleGroups\n  line 47: field id not found in type rulefmt.RuleGroups\n  line 48: field links not found in type rulefmt.RuleGroups\n  line 49: field liveNow not found in type rulefmt.RuleGroups\n  line 50: field panels not found in type rulefmt.RuleGroups\n  line 1630: field refresh not found in type rulefmt.RuleGroups\n  line 1631: field schemaVersion not found in type rulefmt.RuleGroups\n  line 1632: field style not found in type rulefmt.RuleGroups\n  line 1633: field tags not found in type rulefmt.RuleGroups\n  line 1634: field templating not found in type rulefmt.RuleGroups\n  line 1666: field time not found in type rulefmt.RuleGroups\n  line 1670: field timepicker not found in type rulefmt.RuleGroups\n  line 1671: field timezone not found in type rulefmt.RuleGroups\n  line 1672: field title not found in type rulefmt.RuleGroups\n  line 1673: field uid not found in type rulefmt.RuleGroups\n  line 1674: field version not found in type rulefmt.RuleGroups\n  line 1675: field weekStart not found in type rulefmt.RuleGroups"`

**Comment by featheredtoast** [comment]
thanks for the catch and the kind words - seems I inadvertently updated power.yml instead of power.json in the last batch of updates - should be working now!
