### ISSUE TITLE
some issues after setup with missing/wrong data 

### ISSUE THREAD

**Issue by Aureliolo** [featheredtoast/satisfactory-monitoring#2]
Hey there
First off, thank you very much for the amazing collection of tools and easy to follow setup!

I installed on my system and generally seems to all working after some tweaking on the compose file in terms of vars and ports etc. 

But I see some recurring(every few seconds) errors in the logs of frmcompanion:

```
frmcompanion  | 2024/10/21 20:48:45 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
frmcompanion  | 2024/10/21 20:48:52 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
frmcompanion  | 2024/10/21 20:48:59 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
frmcompanion  | 2024/10/21 20:49:06 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
frmcompanion  | 2024/10/21 20:49:13 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
frmcompanion  | 2024/10/21 20:49:20 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
frmcompanion  | 2024/10/21 20:49:26 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
frmcompanion  | 2024/10/21 20:49:33 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
frmcompanion  | 2024/10/21 20:49:40 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
frmcompanion  | 2024/10/21 20:49:47 error reading factory buildings from FRM: json: cannot unmarshal array into Go struct field BuildingDetail.PowerInfo of type exporter.PowerInfo
```

Also in Grafana there are some parts that don't really make sense atm, maybe due to 1.0 changing stuff?

![{F2B0C332-5888-481A-9EA6-C1A10AA02856}](https://github.com/user-attachments/assets/bb4e1d4d-85e4-4bfe-b646-19e1ea98f09c)
Power some graphs not loading at all, but it does detect the amount of buildings etc. possibly connected to the error above in log?

![{6D20F187-A1F1-429A-A675-D31332862463}](https://github.com/user-attachments/assets/9dc53c13-93b3-4075-a942-e151c8e60db5)

Storage the map isn't loading regardless of if I select an item or not

![{C3F7E2CB-96A6-423B-AE97-E72331E4F6CD}](https://github.com/user-attachments/assets/65cd72f1-282e-470c-b67b-c2cbe8cf373c)

Trains it can detect them and the stations, but some graphs aren't loading, and they all have the status derailed, but no derailed alerts? 

![{CC66F032-97C6-4D12-B3C4-8C202B18DCBE}](https://github.com/user-attachments/assets/5fceb537-1867-4d03-9c2a-4de9331bc3e8)

Storage featuring a non existing item (possibly new in 1.0 and not yet having metadata or anything like that?)

![{D4ED0F0D-BB00-46B6-9728-91167FFBDD02}](https://github.com/user-attachments/assets/73d45b3d-4ed9-4a31-a1e2-0be67bec2e77)

Also missing item names on production.

Those the main ones I noticed when testing :) 
If I can assist in debugging or anything like that I would be glad to help, assuming these are things you can fix ofc and its not just for example the monitoring mod that simply isn't fully working yet for 1.0

**Comment by featheredtoast** [comment]
The errors you're seeing about parsing are legit, FRM's latest fixes no longer come with power. With 1.0 things are in flux a little bit, the FRM folks should be back this week to take a look at the power stuff and hopefully get that restored. Both that mod and this stack are both in active development, I pushed up a few fixes just today.

> Power graphs

You have two circuits: circuit  and circuit 3, but the default dashboard's circuit is selected. In the upper right corner of the screen you should also be able to select circuit. Judging from building counts, you should be interested in circuit 3.

> status derailed, but no derailed alerts?

are the trains actually derailed? there are two settings here: train status (a text string) and derailed (a boolean) - the alerts come from this. This sounds like an FRM bug somewhere.

> missing item names on production.

quite possibly an issue with new items in 1.0 - this should be resolved once FRM is able to deliver all the items. Would you mind inspecting the raw `/getStorageInv` json data and confirming that you see <MISSING S STRING TABLE ENTRY> in the json?

Storage is fixed.

**Comment by Aureliolo** [comment]
> The errors you're seeing about parsing are legit, FRM's latest fixes no longer come with power. With 1.0 things are in flux a little bit, the FRM folks should be back this week to take a look at the power stuff and hopefully get that restored. Both that mod and this stack are both in active development, I pushed up a few fixes just today.
> 
Happy to hear! Will update later today or tomorrow then to the new versions.

> > Power graphs
> 
> You have two circuits: circuit and circuit 3, but the default dashboard's circuit is selected. In the upper right corner of the screen you should also be able to select circuit. Judging from building counts, you should be interested in circuit 3.
> 

True, completely missed that part of selecting it, doesn't change anything tough actually. 
![{C56C0F3A-8636-4F8E-B9A2-4DECB822059F}](https://github.com/user-attachments/assets/9318ce1f-1278-49ed-90da-37ca66bf36f1)
This is when i select circuit 3. the map itself does correctly update but other fields stay empty.

> > status derailed, but no derailed alerts?
> 
> are the trains actually derailed? there are two settings here: train status (a text string) and derailed (a boolean) - the alerts come from this. This sounds like an FRM bug somewhere.

Nope no derailed anything. all of them are working and traveling constantly. alerts themselves are also not sent out or rather in alertmanager i only see alerts to underproduction/overconsumptuon. no train alerts. (wouldn't expect any for our world) but the panel shows them as derailed still. or maybe im misinterpreting it?

> > missing item names on production.
> 
> quite possibly an issue with new items in 1.0 - this should be resolved once FRM is able to deliver all the items. Would you mind inspecting the raw `/getStorageInv` json data and confirming that you see in the json?
> 
/getStorageInv over API call? or ingame in chat or something?

> Storage is fixed.
TYVM!

**Comment by featheredtoast** [comment]
The power thing may be a mismatch between how power is reported in FRM, and that mod should update pretty soon to have consistent power IDs - Tracked here: https://github.com/porisius/FicsitRemoteMonitoring/issues/98

Train data issues are being tracked here: https://github.com/porisius/FicsitRemoteMonitoring/issues/99

We're discussing item name issues here https://github.com/porisius/FicsitRemoteMonitoring/issues/107

**Comment by Aureliolo** [comment]
Sweet then all should be fixed down the line :) Do you want to keep this open or close it? both fine for me.

**Comment by featheredtoast** [comment]
I'll keep it open for now, I suspect there'll be some cleanup to do once a few of the above are implemented as they may change interfaces

**Comment by featheredtoast** [comment]
With the release of FRM 1.1, I've made significant progress on fixing up data here.

Some outstanding issues, but I'll open ticket sin the appropriate repos
