### ISSUE TITLE
alertmanager container stuck on ubuntu

### ISSUE THREAD

**Issue by ivansrbulov** [featheredtoast/satisfactory-monitoring#3]
The alertmanager container *sometimes* gets stuck when loading on ubuntu server.

![image](https://github.com/user-attachments/assets/bcbe30ad-756a-4a21-868e-7e9f8ce4e500)

I have tried restarting the server, restarting docker, and deleting the files and starting again. Sometimes the compose runs successfully, but mostly it does not. When it does, there is no dashboard at the web address.

**Comment by featheredtoast** [comment]
Have you updated the docker-compose file at all? you're somehow missing the actual alertmanager image, there should be 8 images (+ the default network):

<img width="1258" alt="Screenshot 2024-11-03 at 3 06 12 PM" src="https://github.com/user-attachments/assets/74f01002-a609-44d3-9d82-bb81b7a3de0e">

What versions of docker/docker compose are you running?

**Comment by ivansrbulov** [comment]
Thanks for the v quick response. So I reset the server fully, reinstalled docker engine, and recloned the git. Only change made at all was to create the .env file with the `FRM_HOST=` arg. At first run, I did indeed have 9 images including the network, but it also got stuck on alertmanager. I cancelled the process (ctrl+c) but that then caused massive performance issues. 

I then rebooted, reran the compose command, and just had 8. They did then run:

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/47219664-1faa-4f59-af77-61e16a679d47">

~~But the webpage at [serverip]:3000 does not load anything.~~ EDIT: Sorry, the webpage issue was a firewall rule problem that I have resolved. It does now run, but it did not work at first as I mentioned I had to reboot my VPS after having issues running it on first compose, and then subsequent system issues which necessitated a reboot. I even had the error `sudo: unable to resolve host ubuntu: Temporary failure in name resolution` when I tried to `sudo reboot`! 

The dashboard looks like this which I think is expected post 1.0 update? 
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/c7466743-6955-42ed-b02a-029d84bf89c7">

**Comment by featheredtoast** [comment]
what version of the mod are you running? there have been updates that resolve the above issue as well. The latest (or at least 1.2.0) now have correct power info as well.

**Comment by ivansrbulov** [comment]
Version 1.2.0 according to the `.uplugin`. I installed the mod yesterday, no previous installs on the server or other mods.

```
[/](http://xx.xx.xx.xx:27012/fs/)[steamcmd](http://xx.xx.xx.xx:27012/fs/steamcmd/)/[satisfactory](http://xx.xx.xx.xx:27012/fs/steamcmd/satisfactory/)/[FactoryGame](http://xx.xx.xx.xx:27012/fs/steamcmd/satisfactory/FactoryGame/)/[Mods](http://xx.xx.xx.xx:27012/fs/steamcmd/satisfactory/FactoryGame/Mods/)/FicsitRemoteMonitoring/
{
	"FileVersion": 3,
	"Version": 1,
	"VersionName": "1.2.0",
	"SemVersion": "1.2.0",
	"AcceptsAnyRemoteVersion": true,
	"FriendlyName": "Ficsit Remote Monitoring",
	"Description": "Statistical and GeoLocation Monitoring for Satisfactory",
	"Category": "Modding",
	"CreatedBy": "Porisius",
	"CreatedByURL": "",
	"DocsURL": "https://docs.ficsit.app/ficsitremotemonitoring/latest/index.html",
	"MarketplaceURL": "",
	"SupportURL": "https://github.com/porisius/FicsitRemoteMonitoring",
	"CanContainContent": true,
	"IsBetaVersion": false,
	"IsExperimentalVersion": false,
	"Installed": false,
	"Modules": [
		{
			"Name": "FicsitRemoteMonitoring",
			"Type": "Runtime",
			"LoadingPhase": "Default"
		}
	],
	"Plugins": [
		{
			"Name": "SML",
			"SemVersion": "^3.8.0",
			"Enabled": true
		}
	],
	"GameVersion": ">=365306",
	"RequiredOnRemote": false
}
```

I can try to reinstall the plugin and see if that resolves things and report back. Let me know if there are other troubleshooting steps I can go through before coming back.

**Comment by featheredtoast** [comment]
No that looks OK to me. It's possible circuit 0 is not your main circuit, but has no power info. Your system appears to be working otherwise. Try selecting a different circuit at the top.

**Comment by ivansrbulov** [comment]
I was having server slowdown issues so I upgraded (from 1 vCore & 1GB RAM to 2vCores & 2GB RAM) which it seems was causing the issues before, I reinstalled it on the new VPS and it all worked flawlessly, so that issue has been solved. Might be worth adding in the README that 2GBs of RAM is the minimum requirement to run the dashboard because clearly that cannot be assumed with people like me using it!

On the info on the dashboard that remains busted with some things working, see screenshots below. Circuit 0 is the main circuit as can be seen by the number of buildings. I apologise for my server name.

**EDIT: Images removed to hide IP.**

**Comment by featheredtoast** [comment]
No worries about your session name, I find it humorous! Your save your rules and all that :)

so... weirdness is happening here:
your metrics collection is *partially* working - all the location data is pulled from the cache side of things. This seems to be populating all the correct places on that side.

I was expecting the companion's graphs to be blank across the board (that's your prometheus datasource), but you've got production graphs which means some of the companion metrics are making it through at least.

If you access {monitoring-server}:9090, can you query the power metrics directly from prometheus and see what's being captured there?
Failing that, {monitoring-server}:9000/metrics can give you a list of *all* collected metrics in a flat text file list.

Do you see those?

**Comment by ivansrbulov** [comment]
I can indeed access prometheus at :9090 and query power:

**EDIT: Image removed to hide IP.**

And this is /metrics:
<img width="1453" alt="image" src="https://github.com/user-attachments/assets/45a2c04d-ae1f-45a6-8371-9b24cdeb37ec">

If useful, have attached the whole /metrics for you to take a look at:
[metrics.txt](https://github.com/user-attachments/files/17622251/metrics.txt)

**Comment by featheredtoast** [comment]
strangely your metrics.txt doesn't actually hold any metrics, despite there being power metrics in prometheus. Are you seeing any errors in the companion logs? `docker compose logs frmcompanion`

**Comment by ivansrbulov** [comment]
haha yes, full relevant terminal output attached

**EDIT: Log removed to hide IP.**

**Comment by featheredtoast** [comment]
ah yeah the 404 responses are a bug in the FRM mod - that release will be fixed soon. but that shouldn't affect things too much.

I believe the`'` mark here is the issue in the data filtering - I'll see what I can do to scrub or escape non-alphanumerics from the session names.

**Comment by ivansrbulov** [comment]
sounds good, thanks so much for being so responsive and taking a look! let me know when and I can start from scratch again and see if that fixes the issue, I'll leave this open until then.

**Comment by featheredtoast** [comment]
Can you try again? I'm sanitizing session names now to allow only for alphanumerics + spaces

**Comment by ivansrbulov** [comment]
I rebooted and git pull'd but unfortunately everything seems the same, screenshot & new logs attached. Let me know if I should completely wipe and try again.

<img width="1180" alt="image" src="https://github.com/user-attachments/assets/242c45da-ca92-45cb-bfde-555e8561f45e">

**EDIT: Log removed to hide IP.**

**Comment by featheredtoast** [comment]
to reboot (destroy+recreate):
`docker compose down`
`docker compose up -d`

**Comment by ivansrbulov** [comment]
Ah yes right sorry, so have done that and it seems to have worked for everything (e.g. trains):
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/8d184a6a-ae4a-41ff-a329-2ee92644c80c">

But only not power: 
<img width="1234" alt="image" src="https://github.com/user-attachments/assets/37b9693c-2aa9-45fa-9655-531a39df7c71">

[docker compose logs 3.txt](https://github.com/user-attachments/files/17627398/docker.compose.logs.3.txt)

**Comment by ivansrbulov** [comment]
Ah yes right sorry, forgot that step -- everything seems to be working now!

**EDIT: Image removed to hide IP.**

404 errors continue in the logs, as expected 
**EDIT: Log removed to hide IP.**

**Comment by featheredtoast** [comment]
great glad to hear it! The 404's should disappear in a future version of the mod itself, it's incorrectly reporting back 404's for empty datasets
